{% set version = "0.3.4.0" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0c/linux-pandoc_2_6.tar.gz  # [linux64]
  sha256: fb7fb47f6892b02150f3e4bf1610d3ea1e02ce23562b374e3617139ce5758ace  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0c/macos-pandoc_2_6.tar.gz  # [osx]
  sha256: fe4ab216fee3cf87f95ca6199341d7638262e73bc25574de0a4525ac7ee2f2c3  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0c/windows-x86_64-pandoc_2.6.zip  # [win]
  sha256: 4ee21c1321fee42283dbd913675e8029b5153ab0f0ef83fa082533b1211fc0da  # [win]

build:
   number: 3

requirements:
  run:
    - pandoc >=2.6,<=2.7

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
