{% set version = "0.3.4.1" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.1/linux-pandoc_2_7_2.tar.gz  # [linux64]
  sha256: 6424c97656b4f9bd888cc8778fd64731f254a570632e2609a157ef21d212d4fe  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.1/macos-pandoc_2_7_2.tar.gz  # [osx]
  sha256: e8fbb9459ba6f74b535babb80957abf4b7cc314b6495dbcfe483fc61d21fc8f0  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.1/windows-x86_64-pandoc_2.7.zip  # [win]
  sha256: 836277468b11527da159cc6d4091758e31744ca73c337243f45b67678e235e48  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >=2.7.2,<=2.8

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
