{% set version = "0.3.4.0" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0b/linux-pandoc_2_5.tar.gz  # [linux64]
  sha256: 84c89b892a79a1f372a1b4e49b47a01995ab436914967fe778d021bf5b7b712b  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0b/macos-pandoc_2_5.tar.gz  # [osx]
  sha256: 646d284cf95b447e700bf8a7f35f93b99e9ecbfaed099efa1f7341aa6b7ef894  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0b/windows-x86_64-pandoc_2.5.zip  # [win]
  # https://www.virustotal.com/#/file/bd0da619b39855f80a19629e9136dd59926d29eada67f83842a0dd28150e0026/detection
  sha256: bd0da619b39855f80a19629e9136dd59926d29eada67f83842a0dd28150e0026  # [win]

build:
   number: 1

requirements:
  run:
    - pandoc >=2.5,< 2.6

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
