{% set version = "0.3.6.0" %}
{% set pandoc = "2.9" %}
{% set pandoc0 = "2_9" %}
{% set pandoc1 = "2.10" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}/linux-pandoc_{{ pandoc0 }}.tar.gz  # [linux64]
  sha256: 73d6caa0050f9e95006e121c64994d215b1a55dae63f8b5fd15f2ec2d24319ed  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}/macos-pandoc_{{ pandoc0 }}.tar.gz  # [osx]
  sha256: 588db3a4274e6952dce88aeef30c01c287e8c3466797dcf4cfdc43e5c8659623  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}/windows-x86_64-pandoc_{{ pandoc }}.zip  # [win]
  sha256: 62001670173e71746597ad52c2baa9813f1ddd52f83c820bace30dc7b567e29f  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
