{% set version = "0.3.4.0.3" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0d/linux-pandoc_2_7.tar.gz  # [linux64]
  sha256: 8d220224c49c7d73e26260219a7ff16fa82bbce34314be3d3628d4664f02cf20  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0d/macos-pandoc_2_6.tar.gz  # [osx]
  sha256: 0ff1a58cbc2579da5a55013b583831e1b1d8bd1a58c91be2e632f6d598aecf49  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.4.0d/windows-x86_64-pandoc_2.7.zip  # [win]
  sha256: daa8cb6c2a703b5a17e161bf6c4286f352a1149999dd0686e1c82209a1cfa7e0  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >=2.7,<=2.8

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
