{% set name = "py-pandoc-crossref" %}
{% set version = "0.3.6.0" %}
# {% set dep_ver = "0.3.5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d69f77841a828170834001b0457b5bcc8db630cb3d47824a066f4714983ba0e8
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandoc-crossref ={{ version }}
    - py-pandoc >=2.9,<2.10

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/kiwi0fruit/py-pandoc-crossref
  license: "GPLv2+"
  license_family: GPL
  license_file: LICENSE
  summary: "Installs pandoc-crossref conda package in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-pandoc-crossref
  dev_url: https://github.com/kiwi0fruit/py-pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
