{% set name = "py-pandoc-crossref" %}
{% set version = "0.3.4.0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d11c4e52454192b699e75e052e5cfe24b33d73e2c1d33053ec6748c005efc39
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandoc-crossref ={{ version }}
    - py-pandoc >=2.6,<2.7

test:
  commands:
    - pandoc-crossref --version
    - pandoc-crossref --help

about:
  home: https://github.com/kiwi0fruit/py-pandoc-crossref
  license: "GPLv2+"
  license_family: GPL
  license_file: LICENSE
  summary: "pandoc-crossref in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-pandoc-crossref
  dev_url: https://github.com/kiwi0fruit/py-pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
